steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/perceptor-scanner/perceptor-scanner', './cmd/perceptor-scanner/perceptor-scanner.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-scanner'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-scanner:latest', './cmd/perceptor-scanner/.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-scanner:latest']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/perceptor-imagefacade/perceptor-imagefacade', './cmd/perceptor-imagefacade/perceptor-imagefacade.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-scanner'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-imagefacade:latest', './cmd/perceptor-imagefacade/.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-imagefacade:latest']
